### ISSUE TITLE
ERROR:  pgroonga: similar search available only in index scan

### ISSUE THREAD

**Issue by oyhan** [JoyMoe/PGroonga.EntityFrameworkCore#4]
Hi
I'm using pgroonga and PostgreSQL 12.5
I have a table with 2 Indexed column names "Title" and "Description"
They are both indexed with pgroonga
but when I ran this query :
SELECT * FROM "Reviews" WHERE "Title" &@* 'بو';
the debugger says :

ERROR:  pgroonga: similar search available only in index scan
SQL state: 0A000
And when add the EXPLAIN keyword :
"Seq Scan on ""Reviews"" (cost=10000000000.00..10000000001.76 rows=1 width=188)"
" Filter: (""Title"" &@* 'بو'::text)"
"JIT:"
" Functions: 4"
" Options: Inlining true, Optimization true, Expressions true, Deforming true"
Unfortunately PostgreSql uses "Seq Scan to run the query even when I execute
SET enable_seqscan = OFF;

For other column ("Description") it will be OK only when I run SET enable_seqscan = OFF;

Im new in PostgreSQL and pgroonga
Thanks for your tips

**Comment by kinosang** [comment]
It might be caused by a weird index. Try delete the Index created via `.HasIndex().HasMethod("pgroonga")` and re-create it manually.

sample SQL here:

```sql
CREATE INDEX "IX_REVIEWS_TITLE"
       ON "Reviews"
       USING pgroonga ("Title");
```

more info here: https://pgroonga.github.io/reference/create-index-using-pgroonga.html

**Comment by oyhan** [comment]
> It might be caused by a weird index. Try delete the Index created via `.HasIndex().HasMethod("pgroonga")` and re-create it manually.
> 
> sample SQL here:
> 
> ```sql
> CREATE INDEX "IX_REVIEWS_TITLE"
>        ON "Reviews"
>        USING pgroonga ("Title");
> ```
> 
> more info here: https://pgroonga.github.io/reference/create-index-using-pgroonga.html

I've done that but it's got like Description column now! I should run the  :
`SET enable_seqscan = OFF` 
to escape from that error.

**Comment by kinosang** [comment]
Have you tried re-creating the index on `Description` manually?

**Comment by oyhan** [comment]
> Have you tried re-creating the index on `Description` manually?

yes
the same way you said for `Title `

**Comment by kinosang** [comment]
see this SO question, https://stackoverflow.com/questions/5203755/why-does-postgresql-perform-sequential-scan-on-indexed-column/5203827

`SET enable_seqscan = OFF` is the only way I known to avoid the problem.

**Comment by oyhan** [comment]
> `SET enable_seqscan = OFF` is the only way I known to avoid the problem.

Thanks for your attention 
I've read that SO .
Is there any way to embed the `SET enable_seqscan = OFF` to my entity framework query to avoid this error?

**Comment by kinosang** [comment]
you can set via `postgresql.conf`

**Comment by oyhan** [comment]
Can you give more clues, please?

**Comment by kinosang** [comment]
Just modify `postgresql.conf` and add `enable_seqscan = off`

see here https://www.postgresql.org/docs/11/runtime-config-query.html

**Comment by oyhan** [comment]
According to the documentation you sent : 
`Enables or disables the query planner's use of sequential scan plan types. **It is impossible to suppress sequential scans entirely**, but turning this variable off discourages the planner from using one if there are other methods available. The default is on.`

After changing the configuration and turning off the `seqscan` it's entirely using the sequential scan method  ha ha ha
and

**Comment by kinosang** [comment]
Try set `random_page_cost = 1.1`, it may help.

You can try to `explain` the raw SQL ef generated ( copy from your console logs ) also.

https://dba.stackexchange.com/questions/152612/postgresql-is-not-using-index-with-large-data

https://stackoverflow.com/questions/23166778/how-to-force-postgresql-to-use-my-index

That's all my solutions I when I got a seqscan exception. if they do not solve your problems, I have no idea.
